const RESET_EVENTS = 'RESET_EVENTS';
const ADD_EVENT = 'ADD_EVENT';
const OPEN_DIALOG = 'OPEN_DIALOG';
const CLOSE_DIALOG = 'CLOSE_DIALOG';

export default {
    RESET_EVENTS,
    ADD_EVENT,
    OPEN_DIALOG,
    CLOSE_DIALOG
}